PLATFORM_PATH := device/tigermedia/tigerbox

# CPU

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT :=  cortex-a9

# Partitions

BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_BOOTIMAGE_PARTITION_SIZE := 20971520
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 629145600
BOARD_USERDATAIMAGE_PARTITION_SIZE := 6798966784
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_CACHEIMAGE_PARTITION_SIZE := 629145600

# Kernel

TARGET_PREBUILT_KERNEL := $(PLATFORM_PATH)/kernel/zImage
BOARD_KERNEL_CMDLINE := init=/init
BOARD_KERNEL_BASE := 0x00008000
BOARD_KERNEL_PAGESZE := 16384
BOARD_KERNEL_SEPARATED_DT := false
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01c00000 --tags_offset 0xffc88000

# Storage

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_RECOVERY_FSTAB := $(PLATFORM_PATH)/recovery.fstab
RECOVERY_SDCARD_ON_DATA := true

# TWRP-specific

TW_NO_SCREEN_TIMEOUT := true
TW_THEME := landscape_mdpi
BOARD_HAS_NO_REAL_SDCARD := true
